### ISSUE TITLE
Make sure export map function can render exactly the same image seen on screen (including some of the shader effects)

### ISSUE THREAD

**Issue by Zematus** [Zematus/Worlds#198]

**Comment by nsmonagh** [comment]
I'm guessing it will be more complex than just painting the shader overlay over the map texture like you did in 86e17ecd237121d58d6620109866cdeeb6694496 with the map overlay?

**Comment by Zematus** [comment]
yeah. so, the way I do it, I just mix the generated map texture with the overlay texture and put the result in a new one. But what you see in the screen is actually the textures plus a shader effect added through a material. The shader is applied through the video card so it never gets drawn into the texture.

I'm not sure what would be the best approach to solve this. What I was thinking is actually rendering the material into a texture as it where a screen (there's a way to do that in Unity) and then copying that texture into a file. But this is a very complex solution and maybe there's an easier way to do it

**Comment by Zematus** [comment]
Figured out a way to do this easily using Graphics.Blit. Also added map scaling for good measure :)
